import {
  Activity, Bike, BookOpen, Brain, BriefcaseBusiness, Clock3, Coffee, Droplets, Dumbbell, Flame,
  Footprints, GraduationCap, HeartPulse, Languages, Medal, Moon, Music, NotebookPen, PersonStanding,
  Smartphone, Target, Timer, Trophy, Zap,
} from "lucide-react";
import type { MetricIconName } from "../shared/schema";

export const metricIcons = {
  activity: Activity,
  bike: Bike,
  "book-open": BookOpen,
  brain: Brain,
  briefcase: BriefcaseBusiness,
  clock: Clock3,
  coffee: Coffee,
  droplets: Droplets,
  dumbbell: Dumbbell,
  flame: Flame,
  footprints: Footprints,
  "graduation-cap": GraduationCap,
  "heart-pulse": HeartPulse,
  languages: Languages,
  medal: Medal,
  moon: Moon,
  music: Music,
  "notebook-pen": NotebookPen,
  "person-standing": PersonStanding,
  smartphone: Smartphone,
  target: Target,
  timer: Timer,
  trophy: Trophy,
  zap: Zap,
} satisfies Record<MetricIconName, typeof Activity>;

export const metricIconOptions: Array<{ name: MetricIconName; label: string }> = [
  { name: "activity", label: "Activity" },
  { name: "bike", label: "Cycling" },
  { name: "book-open", label: "Book" },
  { name: "brain", label: "Focus" },
  { name: "briefcase", label: "Work" },
  { name: "clock", label: "Clock" },
  { name: "coffee", label: "Coffee" },
  { name: "droplets", label: "Water" },
  { name: "dumbbell", label: "Dumbbell" },
  { name: "flame", label: "Flame" },
  { name: "footprints", label: "Walking" },
  { name: "graduation-cap", label: "Study" },
  { name: "heart-pulse", label: "Health" },
  { name: "languages", label: "Language" },
  { name: "medal", label: "Medal" },
  { name: "moon", label: "Sleep" },
  { name: "music", label: "Music" },
  { name: "notebook-pen", label: "Writing" },
  { name: "person-standing", label: "Standing" },
  { name: "smartphone", label: "Screen time" },
  { name: "target", label: "Target" },
  { name: "timer", label: "Timer" },
  { name: "trophy", label: "Trophy" },
  { name: "zap", label: "Energy" },
];
